language: ruby
rvm:
  - "1.9.3"
env:
  - DB=mysql DATABASE_URL="mysql://@localhost/test"
  - DB=pgsql DATABASE_URL="postgres://postgres@localhost/test"
  - DB=sqlite DATABASE_URL="sqlite::memory:"
  - JS=true DISPLAY=":99.0"
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test;'; fi"
  - sh -c "if [ '$JS' = 'true' ]; then /etc/init.d/xvfb start; fi"
  - sh -c "if [ '$JS' = 'true' ]; then sleep 3; fi"
script: rake travis
