language: ruby
rvm:
  - "1.9.3"
env:
  - DB=mysql DATABASE_URL="mysql://@localhost/test"
  - DB=pgsql DATABASE_URL="postgres://postgres@localhost/test"
  - DB=sqlite DATABASE_URL="sqlite::memory:"
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test;'; fi"
script: bundle exec rspec spec
