language: ruby
rvm:
  - "1.9.3"
  - "2.1.0"
env:
  - DB=mysql DATABASE_URL="mysql://@localhost/test"
  - DB=pgsql DATABASE_URL="postgres://postgres@localhost/test"
  - DB=sqlite DATABASE_URL="sqlite::memory:"
  - JS=true
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test;'; fi"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: rake travis

before_install: gem update --remote bundler
matrix:
  exclude:
    - rvm: "1.9.3"
      env: JS=true
